"""This module contains all dataclasses needed to define
physical mail for the SF1601 API.
It is autogenerated by the xsdata package using the official XSD files.
"""

import base64
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional
import uuid

from xsdata.formats.dataclass.context import XmlContext
from xsdata.formats.dataclass.serializers import XmlSerializer
from xsdata.formats.dataclass.serializers.config import SerializerConfig
from xsdata.models.datatype import XmlDate, XmlDateTime


@dataclass(kw_only=True)
class PersonCivilRegistrationIdentifier:
    class Meta:
        namespace = "http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/03/18/"

    value: str = field(
        default="",
        metadata={
            "required": True,
            "pattern": r"((((0[1-9]|1[0-9]|2[0-9]|3[0-1])(01|03|05|07|08|10|12))|((0[1-9]|1[0-9]|2[0-9]|30)(04|06|09|11))|((0[1-9]|1[0-9]|2[0-9])(02)))[0-9]{6})|0000000000",
        },
    )


@dataclass(kw_only=True)
class CompletePostalLabelText:
    class Meta:
        namespace = "http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/05/19/"

    value: str = field(
        default="",
        metadata={
            "required": True,
            "max_length": 34,
        },
    )


@dataclass(kw_only=True)
class CVRnumberIdentifier:
    class Meta:
        namespace = "http://rep.oio.dk/cvr.dk/xml/schemas/2005/03/22/"

    value: str = field(
        default="",
        metadata={
            "required": True,
            "length": 8,
        },
    )


@dataclass(kw_only=True)
class FloorIdentifier:
    class Meta:
        namespace = "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/"

    value: str = field(
        default="",
        metadata={
            "required": True,
            "pattern": r"[1-9]|[1-9][0-9]|KL|ST|kl|st|k[2-9]|K[2-9]",
        },
    )


@dataclass(kw_only=True)
class MailDeliverySublocationIdentifier:
    class Meta:
        namespace = "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/"

    value: str = field(
        default="",
        metadata={
            "required": True,
            "min_length": 1,
            "max_length": 34,
        },
    )


@dataclass(kw_only=True)
class StreetBuildingIdentifier:
    class Meta:
        namespace = "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/"

    value: str = field(
        default="",
        metadata={
            "required": True,
            "pattern": r"([1-9]|[1-9][0-9]|[1-9][0-9]{2})|([1-9][A-Z]|[1-9][0-9][A-Z]|[1-9][0-9]{2}[A-Z])",
        },
    )


@dataclass(kw_only=True)
class SuiteIdentifier:
    class Meta:
        namespace = "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/"

    value: str = field(
        default="",
        metadata={
            "required": True,
            "min_length": 1,
            "max_length": 4,
        },
    )


class CountryIdentificationSchemeType(Enum):
    ISO3166_ALPHA2 = "iso3166-alpha2"
    ISO3166_ALPHA3 = "iso3166-alpha3"
    UN_NUMERIC3 = "un-numeric3"
    IMK = "imk"


@dataclass(kw_only=True)
class DistrictName:
    class Meta:
        namespace = "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/03/15/"

    value: str = field(
        default="",
        metadata={
            "required": True,
            "min_length": 1,
            "max_length": 20,
        },
    )


@dataclass(kw_only=True)
class DistrictSubdivisionIdentifier:
    class Meta:
        namespace = "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/03/15/"

    value: str = field(
        default="",
        metadata={
            "required": True,
            "min_length": 1,
            "max_length": 34,
        },
    )


@dataclass(kw_only=True)
class PostCodeIdentifier:
    class Meta:
        namespace = "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/03/15/"

    value: str = field(
        default="",
        metadata={
            "required": True,
            "pattern": r"[0-9]{4}",
        },
    )


@dataclass(kw_only=True)
class StreetName:
    class Meta:
        namespace = "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/03/15/"

    value: str = field(
        default="",
        metadata={
            "required": True,
            "min_length": 1,
            "max_length": 40,
        },
    )


@dataclass(kw_only=True)
class PostOfficeBoxIdentifier:
    class Meta:
        namespace = "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/05/13/"

    value: Optional[int] = field(
        default=None,
        metadata={
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 9999,
        },
    )


@dataclass(kw_only=True)
class PostalAddressFifthLineText:
    class Meta:
        namespace = "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/05/19/"

    value: str = field(
        default="",
        metadata={
            "required": True,
            "max_length": 34,
        },
    )


@dataclass(kw_only=True)
class PostalAddressFirstLineText:
    class Meta:
        namespace = "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/05/19/"

    value: str = field(
        default="",
        metadata={
            "required": True,
            "max_length": 34,
        },
    )


@dataclass(kw_only=True)
class PostalAddressFourthLineText:
    class Meta:
        namespace = "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/05/19/"

    value: str = field(
        default="",
        metadata={
            "required": True,
            "max_length": 34,
        },
    )


@dataclass(kw_only=True)
class PostalAddressSecondLineText:
    class Meta:
        namespace = "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/05/19/"

    value: str = field(
        default="",
        metadata={
            "required": True,
            "max_length": 34,
        },
    )


@dataclass(kw_only=True)
class PostalAddressSixthLineText:
    class Meta:
        namespace = "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/05/19/"

    value: str = field(
        default="",
        metadata={
            "required": True,
            "max_length": 34,
        },
    )


@dataclass(kw_only=True)
class PostalAddressThirdLineText:
    class Meta:
        namespace = "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/05/19/"

    value: str = field(
        default="",
        metadata={
            "required": True,
            "max_length": 34,
        },
    )


@dataclass(kw_only=True)
class PersonName:
    class Meta:
        namespace = "http://rep.oio.dk/itst.dk/xml/schemas/2006/01/17/"

    value: str = field(
        default="",
        metadata={
            "required": True,
            "min_length": 1,
            "max_length": 130,
        },
    )


@dataclass(kw_only=True)
class EmailAddressIdentifier:
    class Meta:
        namespace = "http://rep.oio.dk/xkom.dk/xml/schemas/2005/03/15/"

    value: str = field(
        default="",
        metadata={
            "required": True,
            "pattern": r"([^>\(\)\[\]\\,;:@\s]{0,191}@[^>\(\)\[\]\\,;:@\s]{1,64})",
        },
    )


@dataclass(kw_only=True)
class CPRnummerIdentifikator:
    class Meta:
        namespace = "urn:oio:adir:dagpenge:2009.07.01"

    value: str = field(
        default="",
        metadata={
            "required": True,
            "pattern": r"((((0[1-9]|1[0-9]|2[0-9]|3[0-1])(01|03|05|07|08|10|12))|((0[1-9]|1[0-9]|2[0-9]|30)(04|06|09|11))|((0[1-9]|1[0-9]|2[0-9])(02)))[0-9]{6})|0000000000",
        },
    )


@dataclass(kw_only=True)
class CVRnummerIdentifikator:
    class Meta:
        namespace = "urn:oio:adir:dagpenge:2009.07.01"

    value: str = field(
        default="",
        metadata={
            "required": True,
            "length": 8,
        },
    )


@dataclass(kw_only=True)
class AfsendelseDatoTid:
    class Meta:
        namespace = "urn:oio:dkal:1.0.0"

    value: Optional[XmlDateTime] = field(
        default=None,
        metadata={
            "required": True,
        },
    )


@dataclass(kw_only=True)
class AfsendelseModtager:
    class Meta:
        namespace = "urn:oio:dkal:1.0.0"

    cpr_nummer_identifikator: Optional[CPRnummerIdentifikator] = field(
        default=None,
        metadata={
            "name": "CPRnummerIdentifikator",
            "type": "Element",
            "namespace": "urn:oio:adir:dagpenge:2009.07.01",
        }
    )
    cvr_nummer_identifikator: Optional[CVRnummerIdentifikator] = field(
        default=None,
        metadata={
            "name": "CVRnummerIdentifikator",
            "type": "Element",
            "namespace": "urn:oio:adir:dagpenge:2009.07.01",
        }
    )


@dataclass(kw_only=True)
class BilagIdentifikator:
    class Meta:
        namespace = "urn:oio:dkal:1.0.0"

    value: str = field(
        default="",
        metadata={
            "required": True,
            "max_length": 10,
        },
    )


@dataclass(kw_only=True)
class FilformatNavn:
    class Meta:
        namespace = "urn:oio:dkal:1.0.0"

    value: str = field(
        default="",
        metadata={
            "required": True,
            "max_length": 10,
        },
    )


@dataclass(kw_only=True)
class MeddelelseFESDmetadataType:
    class Meta:
        target_namespace = "urn:oio:dkal:1.0.0"

    fesddokument_identifikator: Optional[str] = field(
        default=None,
        metadata={
            "name": "FESDdokumentIdentifikator",
            "type": "Element",
            "namespace": "urn:oio:dkal:1.0.0",
        },
    )
    fesdaktoer_identifikator: Optional[str] = field(
        default=None,
        metadata={
            "name": "FESDaktoerIdentifikator",
            "type": "Element",
            "namespace": "urn:oio:dkal:1.0.0",
        },
    )
    fesdsag_identifikator: Optional[str] = field(
        default=None,
        metadata={
            "name": "FESDsagIdentifikator",
            "type": "Element",
            "namespace": "urn:oio:dkal:1.0.0",
        },
    )
    fesdsagsklassifikation_identifikator: Optional[str] = field(
        default=None,
        metadata={
            "name": "FESDsagsklassifikationIdentifikator",
            "type": "Element",
            "namespace": "urn:oio:dkal:1.0.0",
        },
    )


@dataclass(kw_only=True)
class MeddelelseIndholdData:
    class Meta:
        namespace = "urn:oio:dkal:1.0.0"

    value: Optional[str] = field(
        default=None,
        metadata={
            "required": True,
            "format": "base64",
        },
    )


@dataclass(kw_only=True)
class MeddelelseIndholdstypeIdentifikator:
    class Meta:
        namespace = "urn:oio:dkal:1.0.0"

    value: Optional[int] = field(
        default=None,
        metadata={
            "required": True,
        },
    )


@dataclass(kw_only=True)
class MeddelelseSvarEmneIdentifikator:
    class Meta:
        namespace = "urn:oio:dkal:1.0.0"

    value: Optional[int] = field(
        default=None,
        metadata={
            "required": True,
        },
    )


@dataclass(kw_only=True)
class MeddelelseSvarPostkasseIdentifikator:
    class Meta:
        namespace = "urn:oio:dkal:1.0.0"

    value: Optional[int] = field(
        default=None,
        metadata={
            "required": True,
        },
    )


class MeddelelseSvarTypeNavnType(Enum):
    ANGIVET = "angivet"
    IKKE_MULIGT = "ikkeMuligt"
    STANDARD = "standard"


@dataclass(kw_only=True)
class UUID:
    class Meta:
        namespace = "urn:oio:dkal:1.0.0"

    value: str = field(
        default="",
        metadata={
            "required": True,
            "pattern": r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",
        },
    )


@dataclass(kw_only=True)
class VedhaeftningIndholdData:
    class Meta:
        namespace = "urn:oio:dkal:1.0.0"

    value: Optional[bytes] = field(
        default=None,
        metadata={
            "required": True,
            "format": "base64",
        },
    )


@dataclass(kw_only=True)
class VedhaeftningIndholdURLreference:
    class Meta:
        namespace = "urn:oio:dkal:1.0.0"

    value: str = field(
        default="",
        metadata={
            "required": True,
        },
    )


@dataclass(kw_only=True)
class AfsendelseIdentifikator:
    class Meta:
        namespace = "urn:oio:fjernprint:1.0.0"

    value: str = field(
        default="",
        metadata={
            "required": True,
            "min_length": 1,
            "max_length": 38,
        },
    )


@dataclass(kw_only=True)
class AfsenderSystemIdentifikator:
    class Meta:
        namespace = "urn:oio:fjernprint:1.0.0"

    value: str = field(
        default="",
        metadata={
            "required": True,
        },
    )


@dataclass(kw_only=True)
class AllokeringsIdentifikator:
    class Meta:
        namespace = "urn:oio:fjernprint:1.0.0"

    value: Optional[int] = field(
        default=None,
        metadata={
            "required": True,
        },
    )


@dataclass(kw_only=True)
class BilagNavn:
    class Meta:
        namespace = "urn:oio:fjernprint:1.0.0"

    value: str = field(
        default="",
        metadata={
            "required": True,
            "max_length": 300,
        },
    )


@dataclass(kw_only=True)
class BilagSorteringsIndeksIdentifikator:
    class Meta:
        namespace = "urn:oio:fjernprint:1.0.0"

    value: Optional[int] = field(
        default=None,
        metadata={
            "required": True,
        },
    )


@dataclass(kw_only=True)
class BrugerNavn:
    class Meta:
        namespace = "urn:oio:fjernprint:1.0.0"

    value: str = field(
        default="",
        metadata={
            "required": True,
            "min_length": 1,
            "max_length": 2000,
        },
    )


@dataclass(kw_only=True)
class CoNavn:
    class Meta:
        namespace = "urn:oio:fjernprint:1.0.0"

    value: str = field(
        default="",
        metadata={
            "required": True,
            "min_length": 1,
            "max_length": 130,
        },
    )


@dataclass(kw_only=True)
class EnhedTekst:
    class Meta:
        namespace = "urn:oio:fjernprint:1.0.0"

    value: str = field(
        default="",
        metadata={
            "required": True,
            "max_length": 2000,
        },
    )


class FarveShkodeType(Enum):
    SH = "SH"
    FARVE = "Farve"


@dataclass(kw_only=True)
class ForsendelseTypeIdentifikator:
    class Meta:
        namespace = "urn:oio:fjernprint:1.0.0"

    value: Optional[int] = field(
        default=None,
        metadata={
            "required": True,
        },
    )


@dataclass(kw_only=True)
class HasteBrevIndikator:
    class Meta:
        namespace = "urn:oio:fjernprint:1.0.0"

    value: Optional[bool] = field(
        default=None,
        metadata={
            "required": True,
        },
    )


@dataclass(kw_only=True)
class InformationVedAdresseAendringIndikator:
    class Meta:
        namespace = "urn:oio:fjernprint:1.0.0"

    value: Optional[bool] = field(
        default=None,
        metadata={
            "required": True,
        },
    )


class KanalKodeType(Enum):
    DIGITAL_POST = "Digital Post"
    FYSISK_POST = "Fysisk Post"


@dataclass(kw_only=True)
class KonteringsGruppeTekst:
    class Meta:
        namespace = "urn:oio:fjernprint:1.0.0"

    value: str = field(
        default="",
        metadata={
            "required": True,
            "max_length": 2000,
        },
    )


class KuvertTypeKodeType(Enum):
    C4 = "C4"
    C5 = "C5"
    MA = "MA"


@dataclass(kw_only=True)
class KvitteringsEmail:
    class Meta:
        namespace = "urn:oio:fjernprint:1.0.0"

    value: str = field(
        default="",
        metadata={
            "required": True,
            "pattern": r"([^>\(\)\[\]\\,;:@\s]{0,191}@[^>\(\)\[\]\\,;:@\s]{1,64})",
        },
    )


class KvitteringsTypeKodeType(Enum):
    ALLE = "Alle"
    INGEN = "Ingen"
    KUN_FEJL = "Kun fejl"


@dataclass(kw_only=True)
class MasseForsendelseIdentifikator:
    class Meta:
        namespace = "urn:oio:fjernprint:1.0.0"

    value: str = field(
        default="",
        metadata={
            "required": True,
            "min_length": 1,
            "max_length": 38,
        },
    )


@dataclass(kw_only=True)
class MeddelelsesFormatObjektType:
    class Meta:
        target_namespace = "urn:oio:fjernprint:1.0.0"

    any_element: Optional[object] = field(
        default=None,
        metadata={
            "type": "Wildcard",
            "namespace": "##any",
        },
    )


@dataclass(kw_only=True)
class PaatrykAfsenderAdresseIndikator:
    class Meta:
        namespace = "urn:oio:fjernprint:1.0.0"

    value: Optional[bool] = field(
        default=None,
        metadata={
            "required": True,
        },
    )


@dataclass(kw_only=True)
class PaatrykBrevdatoIndikator:
    class Meta:
        namespace = "urn:oio:fjernprint:1.0.0"

    value: Optional[bool] = field(
        default=None,
        metadata={
            "required": True,
        },
    )


@dataclass(kw_only=True)
class PaatrykModtagerAdresseIndikator:
    class Meta:
        namespace = "urn:oio:fjernprint:1.0.0"

    value: Optional[bool] = field(
        default=None,
        metadata={
            "required": True,
        },
    )


class PostKategoriKodeType(Enum):
    PRIORITAIRE = "Prioritaire"
    ECONOMIQUE = "Economique"
    BULK = "Bulk"
    REKOMMANDERET = "Rekommanderet"
    REKOMMANDERET_MED_MODTAGERBEVIS = "Rekommanderet med modtagerbevis"
    FORKYNDELSE = "Forkyndelse"


@dataclass(kw_only=True)
class ReturposthaandteringHosLeverandoerIndikator:
    class Meta:
        namespace = "urn:oio:fjernprint:1.0.0"

    value: Optional[bool] = field(
        default=None,
        metadata={
            "required": True,
        },
    )


@dataclass(kw_only=True)
class SideKvantitet:
    class Meta:
        namespace = "urn:oio:fjernprint:1.0.0"

    value: Optional[int] = field(
        default=None,
        metadata={
            "required": True,
            "min_inclusive": 0,
        },
    )


class SimplexDuplexKodeType(Enum):
    SIMPLEX = "Simplex"
    DUPLEX = "Duplex"


@dataclass(kw_only=True)
class VedhaeftSomIndholdDataIndikator:
    class Meta:
        namespace = "urn:oio:fjernprint:1.0.0"

    value: Optional[bool] = field(
        default=None,
        metadata={
            "required": True,
        },
    )


@dataclass(kw_only=True)
class BrevDato:
    class Meta:
        namespace = "urn:oio:sagdok:3.0.0"

    value: Optional[XmlDate] = field(
        default=None,
        metadata={
            "required": True,
        },
    )


@dataclass(kw_only=True)
class TitelTekst:
    class Meta:
        namespace = "urn:oio:sagdok:3.0.0"

    value: str = field(
        default="",
        metadata={
            "required": True,
        },
    )


@dataclass(kw_only=True)
class UUIDIdentifikator:
    class Meta:
        namespace = "urn:oio:sagdok:3.0.0"

    value: str = field(
        default="",
        metadata={
            "required": True,
        },
    )


@dataclass(kw_only=True)
class CountryIdentificationCodeType:
    class Meta:
        target_namespace = "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/"

    value: str = field(
        default="",
        metadata={
            "required": True,
            "pattern": r"[a-z,A-Z]{2}|[a-z,A-Z]{3}|[0-9]{3}|[0-9]{4}",
        },
    )
    scheme: Optional[CountryIdentificationSchemeType] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        },
    )


@dataclass(kw_only=True)
class MeddelelseFESDmetadata(MeddelelseFESDmetadataType):
    class Meta:
        namespace = "urn:oio:dkal:1.0.0"


@dataclass(kw_only=True)
class MeddelelseSvarTypeNavn:
    class Meta:
        namespace = "urn:oio:dkal:1.0.0"

    value: Optional[MeddelelseSvarTypeNavnType] = field(
        default=None,
        metadata={
            "required": True,
        },
    )


@dataclass(kw_only=True)
class BilagType:
    class Meta:
        target_namespace = "urn:oio:fjernprint:1.0.0"

    bilag_navn: Optional[BilagNavn] = field(
        default=None,
        metadata={
            "name": "BilagNavn",
            "type": "Element",
            "namespace": "urn:oio:fjernprint:1.0.0",
            "required": True,
        },
    )
    filformat_navn: Optional[FilformatNavn] = field(
        default=None,
        metadata={
            "name": "FilformatNavn",
            "type": "Element",
            "namespace": "urn:oio:dkal:1.0.0",
            "required": True,
        },
    )
    bilag_sorterings_indeks_identifikator: Optional[BilagSorteringsIndeksIdentifikator] = field(
        default=None,
        metadata={
            "name": "BilagSorteringsIndeksIdentifikator",
            "type": "Element",
            "namespace": "urn:oio:fjernprint:1.0.0",
            "required": True,
        },
    )
    bilag_identifikator: Optional[BilagIdentifikator] = field(
        default=None,
        metadata={
            "name": "BilagIdentifikator",
            "type": "Element",
            "namespace": "urn:oio:dkal:1.0.0",
        },
    )
    vedhaeftning_indhold_data: Optional[VedhaeftningIndholdData] = field(
        default=None,
        metadata={
            "name": "VedhaeftningIndholdData",
            "type": "Element",
            "namespace": "urn:oio:dkal:1.0.0",
        },
    )
    vedhaeftning_indhold_urlreference: Optional[VedhaeftningIndholdURLreference] = field(
        default=None,
        metadata={
            "name": "VedhaeftningIndholdURLreference",
            "type": "Element",
            "namespace": "urn:oio:dkal:1.0.0",
        },
    )
    vedhaeft_som_indhold_data_indikator: Optional[VedhaeftSomIndholdDataIndikator] = field(
        default=None,
        metadata={
            "name": "VedhaeftSomIndholdDataIndikator",
            "type": "Element",
            "namespace": "urn:oio:fjernprint:1.0.0",
        },
    )


@dataclass(kw_only=True)
class FarveSHKode:
    class Meta:
        namespace = "urn:oio:fjernprint:1.0.0"

    value: Optional[FarveShkodeType] = field(
        default=None,
        metadata={
            "required": True,
        },
    )


@dataclass(kw_only=True)
class KanalKode:
    class Meta:
        namespace = "urn:oio:fjernprint:1.0.0"

    value: Optional[KanalKodeType] = field(
        default=None,
        metadata={
            "required": True,
        },
    )


@dataclass(kw_only=True)
class KuvertTypeKode:
    class Meta:
        namespace = "urn:oio:fjernprint:1.0.0"

    value: Optional[KuvertTypeKodeType] = field(
        default=None,
        metadata={
            "required": True,
        },
    )


@dataclass(kw_only=True)
class KvitteringsTypeKode:
    class Meta:
        namespace = "urn:oio:fjernprint:1.0.0"

    value: Optional[KvitteringsTypeKodeType] = field(
        default=None,
        metadata={
            "required": True,
        },
    )


@dataclass(kw_only=True)
class MeddelelsesFormatObjekt(MeddelelsesFormatObjektType):
    class Meta:
        namespace = "urn:oio:fjernprint:1.0.0"


@dataclass(kw_only=True)
class PostKategoriKode:
    class Meta:
        namespace = "urn:oio:fjernprint:1.0.0"

    value: Optional[PostKategoriKodeType] = field(
        default=None,
        metadata={
            "required": True,
        },
    )


@dataclass(kw_only=True)
class SimplexDuplexKode:
    class Meta:
        namespace = "urn:oio:fjernprint:1.0.0"

    value: Optional[SimplexDuplexKodeType] = field(
        default=None,
        metadata={
            "required": True,
        },
    )


@dataclass(kw_only=True)
class CountryIdentificationCode(CountryIdentificationCodeType):
    class Meta:
        namespace = "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/"


@dataclass(kw_only=True)
class Bilag(BilagType):
    class Meta:
        namespace = "urn:oio:fjernprint:1.0.0"


@dataclass(kw_only=True)
class DokumentParametreType:
    class Meta:
        target_namespace = "urn:oio:fjernprint:1.0.0"

    titel_tekst: Optional[TitelTekst] = field(
        default=None,
        metadata={
            "name": "TitelTekst",
            "type": "Element",
            "namespace": "urn:oio:sagdok:3.0.0",
        },
    )
    uuididentifikator: Optional[UUIDIdentifikator] = field(
        default=None,
        metadata={
            "name": "UUIDIdentifikator",
            "type": "Element",
            "namespace": "urn:oio:sagdok:3.0.0",
        },
    )
    brev_dato: Optional[BrevDato] = field(
        default=None,
        metadata={
            "name": "BrevDato",
            "type": "Element",
            "namespace": "urn:oio:sagdok:3.0.0",
        },
    )
    meddelelses_format_objekt: Optional[MeddelelsesFormatObjekt] = field(
        default=None,
        metadata={
            "name": "MeddelelsesFormatObjekt",
            "type": "Element",
            "namespace": "urn:oio:fjernprint:1.0.0",
        },
    )


@dataclass(kw_only=True)
class PostParametreType:
    class Meta:
        target_namespace = "urn:oio:fjernprint:1.0.0"

    post_kategori_kode: Optional[PostKategoriKode] = field(
        default=None,
        metadata={
            "name": "PostKategoriKode",
            "type": "Element",
            "namespace": "urn:oio:fjernprint:1.0.0",
        },
    )
    allokerings_identifikator: Optional[AllokeringsIdentifikator] = field(
        default=None,
        metadata={
            "name": "AllokeringsIdentifikator",
            "type": "Element",
            "namespace": "urn:oio:fjernprint:1.0.0",
        },
    )
    returposthaandtering_hos_leverandoer_indikator: Optional[ReturposthaandteringHosLeverandoerIndikator] = field(
        default=None,
        metadata={
            "name": "ReturposthaandteringHosLeverandoerIndikator",
            "type": "Element",
            "namespace": "urn:oio:fjernprint:1.0.0",
        },
    )
    information_ved_adresse_aendring_indikator: Optional[InformationVedAdresseAendringIndikator] = field(
        default=None,
        metadata={
            "name": "InformationVedAdresseAendringIndikator",
            "type": "Element",
            "namespace": "urn:oio:fjernprint:1.0.0",
        },
    )
    side_kvantitet: Optional[SideKvantitet] = field(
        default=None,
        metadata={
            "name": "SideKvantitet",
            "type": "Element",
            "namespace": "urn:oio:fjernprint:1.0.0",
        },
    )


@dataclass(kw_only=True)
class PrintParametreType:
    class Meta:
        target_namespace = "urn:oio:fjernprint:1.0.0"

    simplex_duplex_kode: Optional[SimplexDuplexKode] = field(
        default=None,
        metadata={
            "name": "SimplexDuplexKode",
            "type": "Element",
            "namespace": "urn:oio:fjernprint:1.0.0",
        },
    )
    farve_shkode: Optional[FarveSHKode] = field(
        default=None,
        metadata={
            "name": "FarveSHKode",
            "type": "Element",
            "namespace": "urn:oio:fjernprint:1.0.0",
        },
    )
    kuvert_type_kode: Optional[KuvertTypeKode] = field(
        default=None,
        metadata={
            "name": "KuvertTypeKode",
            "type": "Element",
            "namespace": "urn:oio:fjernprint:1.0.0",
        },
    )


@dataclass(kw_only=True)
class TransaktionsParametreIType:
    class Meta:
        target_namespace = "urn:oio:fjernprint:1.0.0"

    transaktions_dato_tid: Optional[str] = field(
        default=None,
        metadata={
            "name": "TransaktionsDatoTid",
            "type": "Element",
            "namespace": "urn:oio:fjernprint:1.0.0",
        },
    )
    masse_forsendelse_identifikator: Optional[MasseForsendelseIdentifikator] = field(
        default=None,
        metadata={
            "name": "MasseForsendelseIdentifikator",
            "type": "Element",
            "namespace": "urn:oio:fjernprint:1.0.0",
        },
    )
    kvitterings_type_kode: Optional[KvitteringsTypeKode] = field(
        default=None,
        metadata={
            "name": "KvitteringsTypeKode",
            "type": "Element",
            "namespace": "urn:oio:fjernprint:1.0.0",
        },
    )
    kvitterings_email: Optional[KvitteringsEmail] = field(
        default=None,
        metadata={
            "name": "KvitteringsEmail",
            "type": "Element",
            "namespace": "urn:oio:fjernprint:1.0.0",
        },
    )


@dataclass(kw_only=True)
class BilagSamlingType:
    class Meta:
        target_namespace = "urn:oio:fjernprint:1.0.0"

    bilag: list[Bilag] = field(
        default_factory=list,
        metadata={
            "name": "Bilag",
            "type": "Element",
            "namespace": "urn:oio:fjernprint:1.0.0",
            "min_occurs": 1,
            "max_occurs": 100,
        },
    )


@dataclass(kw_only=True)
class DokumentParametre(DokumentParametreType):
    class Meta:
        namespace = "urn:oio:fjernprint:1.0.0"


@dataclass(kw_only=True)
class KontaktOplysningType:
    class Meta:
        target_namespace = "urn:oio:fjernprint:1.0.0"

    person_name: Optional[PersonName] = field(
        default=None,
        metadata={
            "name": "PersonName",
            "type": "Element",
            "namespace": "http://rep.oio.dk/itst.dk/xml/schemas/2006/01/17/",
            "required": True,
        },
    )
    co_navn: Optional[CoNavn] = field(
        default=None,
        metadata={
            "name": "CoNavn",
            "type": "Element",
            "namespace": "urn:oio:fjernprint:1.0.0",
        },
    )
    street_name: Optional[StreetName] = field(
        default=None,
        metadata={
            "name": "StreetName",
            "type": "Element",
            "namespace": "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/03/15/",
        },
    )
    street_building_identifier: Optional[StreetBuildingIdentifier] = field(
        default=None,
        metadata={
            "name": "StreetBuildingIdentifier",
            "type": "Element",
            "namespace": "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/",
        },
    )
    floor_identifier: Optional[FloorIdentifier] = field(
        default=None,
        metadata={
            "name": "FloorIdentifier",
            "type": "Element",
            "namespace": "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/",
        },
    )
    suite_identifier: Optional[SuiteIdentifier] = field(
        default=None,
        metadata={
            "name": "SuiteIdentifier",
            "type": "Element",
            "namespace": "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/",
        },
    )
    mail_delivery_sublocation_identifier: Optional[MailDeliverySublocationIdentifier] = field(
        default=None,
        metadata={
            "name": "MailDeliverySublocationIdentifier",
            "type": "Element",
            "namespace": "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/",
        },
    )
    post_code_identifier: Optional[PostCodeIdentifier] = field(
        default=None,
        metadata={
            "name": "PostCodeIdentifier",
            "type": "Element",
            "namespace": "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/03/15/",
        },
    )
    district_subdivision_identifier: Optional[DistrictSubdivisionIdentifier] = field(
        default=None,
        metadata={
            "name": "DistrictSubdivisionIdentifier",
            "type": "Element",
            "namespace": "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/03/15/",
        },
    )
    post_office_box_identifier: Optional[PostOfficeBoxIdentifier] = field(
        default=None,
        metadata={
            "name": "PostOfficeBoxIdentifier",
            "type": "Element",
            "namespace": "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/05/13/",
        },
    )
    postal_address_first_line_text: Optional[PostalAddressFirstLineText] = field(
        default=None,
        metadata={
            "name": "PostalAddressFirstLineText",
            "type": "Element",
            "namespace": "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/05/19/",
        },
    )
    postal_address_second_line_text: Optional[PostalAddressSecondLineText] = field(
        default=None,
        metadata={
            "name": "PostalAddressSecondLineText",
            "type": "Element",
            "namespace": "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/05/19/",
        },
    )
    postal_address_third_line_text: Optional[PostalAddressThirdLineText] = field(
        default=None,
        metadata={
            "name": "PostalAddressThirdLineText",
            "type": "Element",
            "namespace": "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/05/19/",
        },
    )
    postal_address_fourth_line_text: Optional[PostalAddressFourthLineText] = field(
        default=None,
        metadata={
            "name": "PostalAddressFourthLineText",
            "type": "Element",
            "namespace": "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/05/19/",
        },
    )
    postal_address_fifth_line_text: Optional[PostalAddressFifthLineText] = field(
        default=None,
        metadata={
            "name": "PostalAddressFifthLineText",
            "type": "Element",
            "namespace": "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/05/19/",
        },
    )
    postal_address_sixth_line_text: Optional[PostalAddressSixthLineText] = field(
        default=None,
        metadata={
            "name": "PostalAddressSixthLineText",
            "type": "Element",
            "namespace": "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/05/19/",
        },
    )
    country_identification_code: Optional[CountryIdentificationCode] = field(
        default=None,
        metadata={
            "name": "CountryIdentificationCode",
            "type": "Element",
            "namespace": "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/",
            "required": True,
        },
    )


@dataclass(kw_only=True)
class PostParametre(PostParametreType):
    class Meta:
        namespace = "urn:oio:fjernprint:1.0.0"


@dataclass(kw_only=True)
class PrintParametre(PrintParametreType):
    class Meta:
        namespace = "urn:oio:fjernprint:1.0.0"


@dataclass(kw_only=True)
class TransaktionsParametreI(TransaktionsParametreIType):
    class Meta:
        namespace = "urn:oio:fjernprint:1.0.0"


@dataclass(kw_only=True)
class AfsenderAdresse(KontaktOplysningType):
    class Meta:
        namespace = "urn:oio:fjernprint:1.0.0"


@dataclass(kw_only=True)
class BilagSamling(BilagSamlingType):
    class Meta:
        namespace = "urn:oio:fjernprint:1.0.0"


@dataclass(kw_only=True)
class KontaktOplysning(KontaktOplysningType):
    class Meta:
        namespace = "urn:oio:fjernprint:1.0.0"


@dataclass(kw_only=True)
class ModtagerAdresse(KontaktOplysningType):
    class Meta:
        namespace = "urn:oio:fjernprint:1.0.0"


@dataclass(kw_only=True)
class ForsendelseAfsenderType:
    class Meta:
        target_namespace = "urn:oio:fjernprint:1.0.0"

    afsender_adresse: Optional[AfsenderAdresse] = field(
        default=None,
        metadata={
            "name": "AfsenderAdresse",
            "type": "Element",
            "namespace": "urn:oio:fjernprint:1.0.0",
        },
    )


@dataclass(kw_only=True)
class ForsendelseModtagerType:
    class Meta:
        target_namespace = "urn:oio:fjernprint:1.0.0"

    afsendelse_modtager: Optional[AfsendelseModtager] = field(
        default=None,
        metadata={
            "name": "AfsendelseModtager",
            "type": "Element",
            "namespace": "urn:oio:dkal:1.0.0",
        },
    )
    modtager_adresse: Optional[ModtagerAdresse] = field(
        default=None,
        metadata={
            "name": "ModtagerAdresse",
            "type": "Element",
            "namespace": "urn:oio:fjernprint:1.0.0",
        },
    )


@dataclass(kw_only=True)
class ForsendelseAfsender(ForsendelseAfsenderType):
    class Meta:
        namespace = "urn:oio:fjernprint:1.0.0"


@dataclass(kw_only=True)
class ForsendelseModtager(ForsendelseModtagerType):
    class Meta:
        namespace = "urn:oio:fjernprint:1.0.0"


@dataclass(kw_only=True)
class KanalUafhaengigeParametreIType:
    class Meta:
        target_namespace = "urn:oio:fjernprint:1.0.0"

    enhed_tekst: Optional[EnhedTekst] = field(
        default=None,
        metadata={
            "name": "EnhedTekst",
            "type": "Element",
            "namespace": "urn:oio:fjernprint:1.0.0",
        },
    )
    bruger_navn: Optional[BrugerNavn] = field(
        default=None,
        metadata={
            "name": "BrugerNavn",
            "type": "Element",
            "namespace": "urn:oio:fjernprint:1.0.0",
            "required": True,
        },
    )
    konterings_gruppe_tekst: Optional[KonteringsGruppeTekst] = field(
        default=None,
        metadata={
            "name": "KonteringsGruppeTekst",
            "type": "Element",
            "namespace": "urn:oio:fjernprint:1.0.0",
        },
    )
    forsendelse_afsender: Optional[ForsendelseAfsender] = field(
        default=None,
        metadata={
            "name": "ForsendelseAfsender",
            "type": "Element",
            "namespace": "urn:oio:fjernprint:1.0.0",
        },
    )
    paatryk_afsender_adresse_indikator: Optional[PaatrykAfsenderAdresseIndikator] = field(
        default=None,
        metadata={
            "name": "PaatrykAfsenderAdresseIndikator",
            "type": "Element",
            "namespace": "urn:oio:fjernprint:1.0.0",
        },
    )
    paatryk_modtager_adresse_indikator: Optional[PaatrykModtagerAdresseIndikator] = field(
        default=None,
        metadata={
            "name": "PaatrykModtagerAdresseIndikator",
            "type": "Element",
            "namespace": "urn:oio:fjernprint:1.0.0",
        },
    )
    paatryk_brevdato_indikator: Optional[PaatrykBrevdatoIndikator] = field(
        default=None,
        metadata={
            "name": "PaatrykBrevdatoIndikator",
            "type": "Element",
            "namespace": "urn:oio:fjernprint:1.0.0",
        },
    )
    kanal_kode: Optional[KanalKode] = field(
        default=None,
        metadata={
            "name": "KanalKode",
            "type": "Element",
            "namespace": "urn:oio:fjernprint:1.0.0",
        },
    )
    haste_brev_indikator: Optional[HasteBrevIndikator] = field(
        default=None,
        metadata={
            "name": "HasteBrevIndikator",
            "type": "Element",
            "namespace": "urn:oio:fjernprint:1.0.0",
        },
    )


@dataclass(kw_only=True)
class KanalUafhaengigeParametreI(KanalUafhaengigeParametreIType):
    class Meta:
        namespace = "urn:oio:fjernprint:1.0.0"


@dataclass(kw_only=True)
class ForsendelseIType:
    class Meta:
        target_namespace = "urn:oio:fjernprint:1.0.0"

    afsendelse_identifikator: Optional[AfsendelseIdentifikator] = field(
        default=None,
        metadata={
            "name": "AfsendelseIdentifikator",
            "type": "Element",
            "namespace": "urn:oio:fjernprint:1.0.0",
            "required": True,
        },
    )
    forsendelse_type_identifikator: Optional[ForsendelseTypeIdentifikator] = field(
        default=None,
        metadata={
            "name": "ForsendelseTypeIdentifikator",
            "type": "Element",
            "namespace": "urn:oio:fjernprint:1.0.0",
        },
    )
    forsendelse_modtager: Optional[ForsendelseModtager] = field(
        default=None,
        metadata={
            "name": "ForsendelseModtager",
            "type": "Element",
            "namespace": "urn:oio:fjernprint:1.0.0",
        },
    )
    filformat_navn: Optional[FilformatNavn] = field(
        default=None,
        metadata={
            "name": "FilformatNavn",
            "type": "Element",
            "namespace": "urn:oio:dkal:1.0.0",
            "required": True,
        },
    )
    meddelelse_indhold_data: Optional[MeddelelseIndholdData] = field(
        default=None,
        metadata={
            "name": "MeddelelseIndholdData",
            "type": "Element",
            "namespace": "urn:oio:dkal:1.0.0",
            "required": True,
        },
    )
    transaktions_parametre_i: Optional[TransaktionsParametreI] = field(
        default=None,
        metadata={
            "name": "TransaktionsParametreI",
            "type": "Element",
            "namespace": "urn:oio:fjernprint:1.0.0",
        },
    )
    dokument_parametre: Optional[DokumentParametre] = field(
        default=None,
        metadata={
            "name": "DokumentParametre",
            "type": "Element",
            "namespace": "urn:oio:fjernprint:1.0.0",
            "required": True,
        },
    )
    kanal_uafhaengige_parametre_i: Optional[KanalUafhaengigeParametreI] = field(
        default=None,
        metadata={
            "name": "KanalUafhaengigeParametreI",
            "type": "Element",
            "namespace": "urn:oio:fjernprint:1.0.0",
        },
    )
    print_parametre: Optional[PrintParametre] = field(
        default=None,
        metadata={
            "name": "PrintParametre",
            "type": "Element",
            "namespace": "urn:oio:fjernprint:1.0.0",
        },
    )
    digital_post_parametre: Optional[str] = field(
        default=None,
        metadata={
            "name": "DigitalPostParametre",
            "type": "Element",
            "namespace": "urn:oio:fjernprint:1.0.0",
        },
    )
    post_parametre: Optional[PostParametre] = field(
        default=None,
        metadata={
            "name": "PostParametre",
            "type": "Element",
            "namespace": "urn:oio:fjernprint:1.0.0",
        },
    )
    bilag_samling: Optional[BilagSamling] = field(
        default=None,
        metadata={
            "name": "BilagSamling",
            "type": "Element",
            "namespace": "urn:oio:fjernprint:1.0.0",
        },
    )


@dataclass(kw_only=True)
class ForsendelseI(ForsendelseIType):
    class Meta:
        namespace = "urn:oio:fjernprint:1.0.0"


def create_physical_mail(
    recipient_cpr: str,
    recipient_name: str,
    street_name: str,
    street_building: str,
    postal_code: str,
    file_content: bytes,
    file_format: str = "pdf",
    country_code: str = "DK",
) -> str:
    return ForsendelseI(
        afsendelse_identifikator=AfsendelseIdentifikator(value=str(uuid.uuid4())),
        forsendelse_type_identifikator=ForsendelseTypeIdentifikator(value=265),  # TODO: What is this?
        forsendelse_modtager=ForsendelseModtager(
            afsendelse_modtager=AfsendelseModtager(
                cpr_nummer_identifikator=CPRnummerIdentifikator(value=recipient_cpr)
            ),
            modtager_adresse=ModtagerAdresse(
                person_name=PersonName(value=recipient_name),
                street_name=StreetName(value=street_name),
                street_building_identifier=StreetBuildingIdentifier(value=street_building),
                post_code_identifier=PostCodeIdentifier(value=postal_code),
                country_identification_code=CountryIdentificationCode(
                    value=country_code,
                    scheme=CountryIdentificationSchemeType.ISO3166_ALPHA2
                )
            )
        ),
        filformat_navn=FilformatNavn(value=file_format),
        meddelelse_indhold_data=MeddelelseIndholdData(
            value=base64.b64encode(file_content).decode("ascii")
        ),
        transaktions_parametre_i=TransaktionsParametreI(),
        dokument_parametre=DokumentParametre()
    )
